### ISSUE TITLE
No box appears on LiveChat and nothing happens

### ISSUE THREAD

**Issue by cinimodphoto** [MysteryBlokHed/TypeCheat#2]
I have tried all the methods listed, the bookmark, the javascript console and nothing works on the console I get the error "Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at <anonymous>:18:5923
(anonymous) @ VM7679:18"

**Comment by MysteryBlokHed** [comment]
Should be fixed now

**Comment by cinimodphoto** [comment]
Hmm I must be doing something wrong. Nothing is happening.

**Comment by MysteryBlokHed** [comment]
Make sure that you're using the new version of the file. If you were using the bookmark, you will need to download the file again.
[(Link to Bookmark)](https://github.com/hackermancool/TypeCheat/blob/master/typecheat-bookmark.html)
If you just want to copy + paste the code into the console, then you can go to the new file [here](https://raw.githubusercontent.com/hackermancool/TypeCheat/master/typecheat.min.js).

**Comment by cinimodphoto** [comment]
Yep I deleted the old bookmark, I tried a different browser, I just now tried what you sent and still nothing.

**Comment by MysteryBlokHed** [comment]
What browser are you using?

**Comment by cinimodphoto** [comment]
I tried brave and chrome
